### ISSUE TITLE
Implement Zeitbedingungen (FV2204)

### ISSUE THREAD

**Issue by hf-aschloegl** [Hochfrequenz/ahbicht#97]
UB1 oder sowas
![grafik](https://user-images.githubusercontent.com/23094997/153556884-941e05b6-f9d9-487e-bbc6-4df04f275f63.png)

https://www.edi-energy.de/index.php?id=38&tx_bdew_bdew%5Buid%5D=1360&tx_bdew_bdew%5Baction%5D=download&tx_bdew_bdew%5Bcontroller%5D=Dokument&cHash=b5562da87f7011f0c386ef3c0dbbdf7a 
Seite 38ff

**Comment by hf-kklein** [comment]
Sehe ich das richtig, dass es sich um hartgecodete Bedingungen handelt? Also es gibt nur `UB1`, `UB2`, `UB3`?

**Comment by hf-aschloegl** [comment]
Glaube schon
